### ISSUE TITLE
Please comment on this Issue!

### ISSUE THREAD

**Issue by githubteacher** [githubteacher/furry-computing-machine#1]
Anything will do!

**Comment by skj99** [comment]
comment ...

**Comment by phil7277** [comment]
So far so good!

**Comment by johnsgill3** [comment]
I want to collaborate!

**Comment by RebecaLM** [comment]
Hi

**Comment by jskravitz** [comment]
this is my comment

**Comment by TDMel** [comment]
OK, anything it is!

**Comment by wdzfortune** [comment]
My comment!

**Comment by luke-pi** [comment]
Comment

**Comment by ksimo2475** [comment]
Hello

**Comment by ElectricCo** [comment]
Hello world

**Comment by glennbuck** [comment]
hi glenn here by user id is glennbuck

**Comment by ew120855** [comment]
Got it

**Comment by githubteacher** [comment]
:tada: @skj99, @phil7277, @johnsgill3, @RebecaLM, @jskravitz, @TDMel, @wdzfortune, @luke-pi, @ksimo2475, @ElectricCo, and @glennbuck are now  repository collaborators. :balloon:

**Comment by timampe** [comment]
Hi Everyone!

**Comment by wdzfortune** [comment]
My first comment!

**Comment by sumanth51** [comment]
Gotcha

**Comment by githubteacher** [comment]
:tada: @ew120855, @timampe, and @sumanth51 are now  repository collaborators. :balloon:

**Comment by jnguyen-td** [comment]
Hello, World!

**Comment by tdesm001** [comment]
Hi, reporting in

**Comment by lawrence-td** [comment]
Checking in.

**Comment by sestucky** [comment]
my comment

**Comment by botany1234** [comment]
Adding my first issue  Hello Everyone!!!

**Comment by Joseph-Kosic** [comment]
I see it.

**Comment by tweedledeecat** [comment]
commenting

**Comment by pjay89** [comment]
comment

**Comment by jameslogan-td** [comment]
Teradata anybody?

**Comment by carolkeough** [comment]
Hello

**Comment by claudiaschreiber** [comment]
comment

**Comment by KimHargett** [comment]
Hello

**Comment by vbrajyaguru** [comment]
Hello!

**Comment by tbuaas** [comment]
howdy!

**Comment by hcanna** [comment]
Great Job Patrick ... Learning so much

**Comment by DaveHomeClass** [comment]
OK

**Comment by pekkakos** [comment]
Yes, Teradata!

**Comment by jackieylam** [comment]
Yay!

**Comment by pratikraj11** [comment]
hello world

**Comment by tweedledeecat** [comment]
commenting.......

**Comment by JG121180** [comment]
my comment

**Comment by susesi** [comment]
Got it

**Comment by githubteacher** [comment]
:tada: @jnguyen-td, @tdesm001, @LawrenceTeradata, @sestucky, @botany1234, @Joseph-Kosic, @tweedledeecat, @pjay89, @jameslogan-td, @carolkeough, @claudiaschreiber, @KimHargett, @vbrajyaguru, @tbuaas, @hcanna, @DaveHomeClass, @pekkakos, @jackieylam, @pratikraj11, @tweedledeecat, and @JG121180 are now  repository collaborators. :balloon:

**Comment by meomy** [comment]
Ok got it now, garyj

**Comment by tatikonda** [comment]
Got it

**Comment by bertsdirt** [comment]
yatzee

**Comment by githubteacher** [comment]
:tada: @susesi, @meomy, @tatikonda, and @bertsdirt are now  repository collaborators. :balloon:

**Comment by diogo-raphael-cravo** [comment]
Please add me as a collaborator!

**Comment by DHoltzman** [comment]
Hi

**Comment by vankiyono** [comment]
hello

**Comment by allthedoll** [comment]
![image](https://cloud.githubusercontent.com/assets/5758031/12924437/dedc10b0-cf0e-11e5-9108-d07dba14d719.png)

**Comment by past97** [comment]
got it!

**Comment by blanoue** [comment]
Commenting on issue

**Comment by githubteacher** [comment]
:tada: @diogo-raphael-cravo, @DHoltzman, @vankiyono, @allthedoll, @past97, and @blanoue are now  repository collaborators. :balloon:

**Comment by harpreetbassi** [comment]
Hi

**Comment by jenjordan** [comment]
Hello

**Comment by komalmathur** [comment]
my comment

**Comment by ghost** [comment]
GOOD

**Comment by lakshmivs** [comment]
Hello

**Comment by ln121570** [comment]
I'm commenting on this issue and I'm Lynn Nichols

**Comment by ghost** [comment]
Hello from Alexander...

**Comment by sjkimace** [comment]
Hi This is Sung Jin Kim. Glad to be here.

**Comment by hiker1220** [comment]
OK

**Comment by vargheel** [comment]
test comment

**Comment by nl186002** [comment]
ok

**Comment by paulsinclair51** [comment]
My comment

**Comment by ghost** [comment]
I'M CONNECTING ON THIS ISSUE MYSELF GHOUSE

**Comment by narbmw** [comment]
no comment

**Comment by dclarkrb** [comment]
Here you go....

**Comment by lynnev1** [comment]
Comment

**Comment by mk121704** [comment]
Added a comment to #1 again

**Comment by jbumgit** [comment]
comment

**Comment by chadseeraty** [comment]
commenting on this issue

**Comment by ss122344** [comment]
comment

**Comment by NickLar59** [comment]
NickLar59  welcome

**Comment by sd122230** [comment]
norning

**Comment by rengs14nathan** [comment]
comment from Renga

**Comment by valliappanrm** [comment]
Please add me as collaborator.

**Comment by githubteacher** [comment]
:tada: @harpreetbassi, @jenjordan, @komalmathur, @lakshmivs, @ln121570, @tdEmpl64, @hiker1220, @vargheel, @nl186002, @paulsinclair121941, @narbmw, @dclarkrb, @lynnev1, @mk121704, @jbumgit, @chadseeraty, and @NickLar59 are now  repository collaborators. :balloon:

**Comment by ghost** [comment]
GHOUSE HERE

**Comment by martinepadilla** [comment]
comment

**Comment by ericfengwu** [comment]
comment

**Comment by githubteacher** [comment]
:tada: @martinepadilla and @ericfengwu are now  repository collaborators. :balloon:

**Comment by tpk543** [comment]
Good going...

**Comment by maru-villanueva** [comment]
New comment on issue #1

**Comment by krishnamachary** [comment]
comment

**Comment by vv186005** [comment]
Trying to comment

**Comment by githubteacher** [comment]
:tada: @tpk543, @maru-villanueva, @krishnamachary, and @vineeya are now  repository collaborators. :balloon:

**Comment by Jaimy1** [comment]
comment

**Comment by JaneBarrett** [comment]
Finally.

**Comment by Lisa-Lisa** [comment]
Hi!

**Comment by githubteacher** [comment]
:tada: @Jaimy1 and @JaneBarrett are now  repository collaborators. :balloon:

**Comment by githubdevoper** [comment]
Cool!

**Comment by ghost** [comment]
Please add me

**Comment by mk121704** [comment]
nice

**Comment by pkhayes** [comment]
Please add me pkhayes

**Comment by kborme** [comment]
Cool

**Comment by githubteacher** [comment]
:tada: @githubdevoper, @DemoGH16, @pkhayes, and @kborme are now  repository collaborators. :balloon:

**Comment by classUser** [comment]
another comment

**Comment by githubteacher** [comment]
:tada: @classUser is now a repository collaborator. :balloon:

**Comment by githubdevoper** [comment]
FYI issue #24

**Comment by lawrence-td** [comment]
Linking to #1

**Comment by lawrence-td** [comment]
## Tasks
- [ ] Do this
- [ ]  And this

**Comment by githubdevoper** [comment]
update

**Comment by lawrence-td** [comment]
# Emoji test

 :smiley_cat:

**Comment by narbmw** [comment]
where do I get the emoji's?

**Comment by crichID** [comment]
@narbmw here is the [emoji cheat sheet](http://emoji.muan.co/)

**Comment by narbmw** [comment]
But how do I get to it from within the issue comment?

**Comment by crichID** [comment]
@narbmw use the : to surround the emoji name so `:smile:` will look like :smile:

**Comment by narbmw** [comment]
:rose: OK, I get it, but I'm not emoji-aware
