### ISSUE TITLE
How to merge with conflicts

### ISSUE THREAD

**Issue by komalmathur** [githubteacher/furry-computing-machine#158]
Can you show how to merge if there are conflicts
Thanks

**Comment by crichID** [comment]
@komalmathur I know Patrick is planning to try to get to this during Q&A. Just in case, here are some resources for you:
- [YouTube Video on Merging which also covers handling conflicts](https://youtu.be/yyLiplDQtf0?list=PLg7s6cbtAD15G8lNyoaYDuKZSKyJrgwB-)
- [Help Article on Merge Conflicts](https://help.github.com/articles/resolving-a-merge-conflict-from-the-command-line/)
