### ISSUE TITLE
Please respond to this issue

### ISSUE THREAD

**Issue by susesi** [githubteacher/furry-computing-machine#3]
Smile please

**Comment by pratikraj11** [comment]
hello

**Comment by jnguyen-td** [comment]
Hello, World!

**Comment by junejlee** [comment]
Add me!

**Comment by wyephani** [comment]
hi

**Comment by ss122344** [comment]
found it!

**Comment by JeferyRoberts** [comment]
Hi there!

**Comment by Lisa-Lisa** [comment]
Hi!

**Comment by sd122230** [comment]
morning!

**Comment by alboise** [comment]
Responding to issue as requested...

**Comment by nikkicastellanos** [comment]
Hello!

**Comment by sjkimace** [comment]
This is Sung Jin Kim. Glad to be here.

**Comment by GitAy360** [comment]
Response

**Comment by kranthi2324** [comment]
That's great

**Comment by githubteacher** [comment]
:tada: @junejlee, @wyephani, @ss122344, @JeferyRoberts, @Lisa-Lisa, @sd122230, @alboise, @nikkicastellanos, @sjkimace, @GitAy360, and @kranthi2324 are now  repository collaborators. :balloon:
