### ISSUE TITLE
Testing out some markdown

### ISSUE THREAD

**Issue by timampe** [githubteacher/furry-computing-machine#31]
# Test Header
1. Numbered item 1
2. Numbered item 2

_Italics_

**Bold**

> Quoted text

`Code Snippet`
## Header 2
- Bullet list item 1
- Bullet list item 2

Link to issue #1 

Adding Issues
- [x] Task 1
- [ ] Task 2

**Comment by timampe** [comment]
@timampe

**Comment by susesi** [comment]
hi Tim. This is Sudhansu
