### ISSUE TITLE
Demo Issue features

### ISSUE THREAD

**Issue by githubteacher** [githubteacher/furry-computing-machine#32]
# Title
- [x] task 1
- [x] task 2

If you haven't already, please be sure to comment on #1.

**Comment by githubteacher** [comment]
@crichID @allthedoll @hcanna your thoughts?

**Comment by glennbuck** [comment]
@blanoue  howdy

**Comment by hcanna** [comment]
@patrickmckenna ... Hello Class

**Comment by crichID** [comment]
@patrickmckenna I think we should add the enhancement label to our issues!

**Comment by blanoue** [comment]
@glennbuck Howdy!

**Comment by allthedoll** [comment]
Don't forget the task of `more cowbell` @githubteacher.

![cowbell](http://metrocrossfit.com/wp-content/uploads/2015/03/Christopher+walken+_a3ca9b723ef5f4ad5c597709df21e309.jpg)

**Comment by maru-villanueva** [comment]
@maru-villanueva

**Comment by botany1234** [comment]
:speak_no_evil:

**Comment by susesi** [comment]
+1

**Comment by glennbuck** [comment]
:santa: 
:space_invader: 
@blanoue

**Comment by hcanna** [comment]
Having :email: open a couple times a day ... improves my productivity :100: :x: more.
