### ISSUE TITLE
Please comment on this issue

### ISSUE THREAD

**Issue by LQDuong** [githubteacher/furry-computing-machine#4]
A comment from lqd

**Comment by LQDuong** [comment]
Comment from LQD

**Comment by rengs14nathan** [comment]
yes..

**Comment by mzieger** [comment]
my comment :-)

**Comment by valliappanrm** [comment]
Please add me as collaborator.

**Comment by githubteacher** [comment]
:tada: @LQDuong, @rengs14nathan, @mzieger, and @valliappanrm are now  repository collaborators. :balloon:
