### ISSUE TITLE
First GitHub class!

### ISSUE THREAD

**Issue by kranthi2324** [githubteacher/furry-computing-machine#48]
# GitHub Demo
#### It is great to attend the class. So eyes on it.
- [x] task1
- [x] task2

Please comment on issue #1

**Comment by kranthi2324** [comment]
Hello @githubteacher please comment on this.

**Comment by kranthi2324** [comment]
:eyes: :smiley:

**Comment by mk121704** [comment]
# now the markdown is working with firefox brower
